spring.application.name=dbmessagedispatcher
app.datasource.jndi-name=jdbc/myappDS
app.mq.jndi-name=eis/wmq/ConnectionFactory
app.mq.dest.res.queue.jndi-name=jms/mq/devqueue2

logging.level.org.springframework.transaction=TRACE
logging.level.org.springframework.jms=DEBUG
logging.level.com.ibm.mq=DEBUG
logging.level.weblogic.transaction=DEBUG

logging.level.org.springframework.jdbc.datasource=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.javax.transaction=DEBUG
logging.level.javax.resource=DEBUG
logging.level.oracle.jdbc=DEBUG
logging.level.oracle.ucp=DEBUG
