spring.application.name=springmqdbapp
app.datasource.jndi-name=jdbc/myappDS
app.mq.jndi-name=eis/wmq/ConnectionFactory
app.mq.dest.ack.queue.jndi-name=jms/mq/devqueue3
app.mq.dest.res.queue.jndi-name=jms/mq/devqueue2
app.mq.source.queue.jndi-name=jms/mq/devqueue1
app.mq.dest.error.queue.jndi-name=jms/mq/deverrorqueue


logging.level.org.springframework.transaction=TRACE
logging.level.org.springframework.jms=DEBUG
logging.level.com.ibm.mq=DEBUG
logging.level.weblogic.transaction=DEBUG

logging.level.org.springframework.jdbc.datasource=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.javax.transaction=DEBUG
logging.level.javax.resource=DEBUG
logging.level.oracle.jdbc=DEBUG
logging.level.oracle.ucp=DEBUG
